SELECT apellido FROM sistema.empleados;
SELECT DISTINCT apellido FROM sistema.empleados;
SELECT * FROM sistema.empleados;
SELECT nombre, apellido FROM sistema.empleados;
SELECT cuil_cuit FROM sistema.empleados;
SELECT CONCAT_WS(' ', nombre, apellido) AS 'Nombre y Apellido' FROM sistema.empleados;
SELECT UPPER(CONCAT_WS(' ', nombre, apellido)) AS 'Nombre y Apellido' FROM sistema.empleados;
SELECT LOWER(CONCAT_WS(' ', nombre, apellido)) AS 'Nombre y Apellido' FROM sistema.empleados;
SELECT nombre, presupuesto FROM sistema.departamentos ORDER BY presupuesto ASC;
SELECT nombre FROM sistema.departamentos ORDER BY nombre ASC;
SELECT nombre FROM sistema.departamentos ORDER BY nombre DESC;
SELECT apellido, nombre FROM sistema.empleados ORDER BY apellido, nombre;
SELECT nombre AS departamento, presupuesto FROM sistema.departamentos ORDER BY presupuesto DESC LIMIT 3;
SELECT nombre AS departamento, presupuesto FROM sistema.departamentos WHERE presupuesto>0  ORDER BY presupuesto ASC LIMIT 3;
SELECT nombre AS departamento, presupuesto FROM sistema.departamentos WHERE presupuesto>=150000  ORDER BY presupuesto ASC;
SELECT nombre AS departamento, presupuesto FROM sistema.departamentos WHERE presupuesto=0;
SELECT nombre AS departamento, presupuesto FROM sistema.departamentos WHERE presupuesto>0 AND (presupuesto<=100000 OR presupuesto>=200000);
SELECT nombre AS departamento, presupuesto FROM sistema.departamentos WHERE presupuesto BETWEEN 100000 AND 200000;
SELECT nombre AS departamento, presupuesto FROM sistema.departamentos WHERE presupuesto NOT BETWEEN 100000 AND 200000;
SELECT CONCAT_WS(' ',e.nombre, e.apellido) AS 'Nombre y Apellido' , d.nombre AS 'Departamento' FROM sistema.empleados AS e JOIN sistema.departamentos AS d WHERE e.id_departamento = d.iddepartamento;
SELECT d.nombre AS 'Departamento', CONCAT_WS(' ',e.nombre, e.apellido) AS 'Nombre y Apellido'  FROM sistema.empleados AS e JOIN sistema.departamentos AS d WHERE e.id_departamento = d.iddepartamento ORDER BY d.nombre, e.nombre;
SELECT DISTINCT d.iddepartamento AS 'Código', d.nombre FROM sistema.empleados AS e JOIN sistema.departamentos AS d ON e.id_departamento = d.iddepartamento; 
SELECT d.nombre FROM sistema.departamentos AS d JOIN sistema.empleados AS e ON e.id_departamento = d.iddepartamento WHERE e.cuil_cuit = '27-38382980-3';
SELECT d.nombre FROM sistema.departamentos AS d JOIN sistema.empleados AS e ON e.id_departamento = d.iddepartamento WHERE e.nombre  = 'Pepe' AND e.apellido = 'Ruiz';
SELECT CONCAT_WS(' ',e.nombre, e.apellido) AS 'Nombre y Apellido' , e.cuil_cuit,  d.nombre AS 'Departamento' FROM sistema.empleados AS e JOIN sistema.departamentos AS d ON e.id_departamento = d.iddepartamento WHERE d.nombre = 'I+D';
SELECT CONCAT_WS(' ',e.nombre, e.apellido) AS 'Nombre y Apellido' , e.cuil_cuit,  d.nombre AS 'Departamento' FROM sistema.empleados AS e JOIN sistema.departamentos AS d ON e.id_departamento = d.iddepartamento WHERE d.nombre = 'I+D' OR d.nombre = 'Contabilidad' OR d.nombre = 'Sistemas' ORDER BY e.nombre;
SELECT CONCAT_WS(' ',e.nombre, e.apellido) AS 'Nombre y Apellido' , d.nombre AS 'Departamento' FROM sistema.empleados AS e JOIN sistema.departamentos AS d ON e.id_departamento = d.iddepartamento WHERE d.nombre = 'I+D' OR d.nombre = 'Contabilidad' OR d.nombre = 'Sistemas' ORDER BY e.nombre;
SELECT CONCAT_WS(' ',e.nombre, e.apellido) AS 'Nombre y Apellido' , d.nombre AS 'Departamento' , d.presupuesto FROM sistema.empleados AS e JOIN sistema.departamentos AS d ON e.id_departamento = d.iddepartamento WHERE d.presupuesto BETWEEN 100000 AND 200000 ORDER BY d.presupuesto ASC;

